profiles:
  active: local

spring:
  datasource:
    username: wewk
    password:
    url: jdbc:h2:tcp://localhost/~/wewk
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # jpa hibernate 에서 생성한 쿼리 system log 로 출력
        show_sql: false
        format_sql: true
        #use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

  thymeleaf:
    check-template: true
    prefix: classpath:templates/
    suffix: .html
    cache: false

